name: Update repositories status

on:
  workflow_dispatch:
  schedule:
  - cron: '*/10 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2
      with:
        repository: lukaszraczylo/actions-dashboard
        path: generator

    - name: Install yq
      run: |
        sudo wget -LO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
    - name: Generate
      run: |
        cd generator;
        ./generate.sh -o ${{ github.workspace }}/README.md -i ${{ github.workspace }}/repositories-list.md
        cd ${{ github.workspace }}; \
        if [ -z "$(git status -s -- repositories-list.md)" ]; then
          echo No changes to commit
          exit 0
        fi
        git config user.email "check-action@github"
        git config user.name "check-action"
        git add README.md
        git commit -m "Update dashboard markdown"
        git push origin master